### ISSUE TITLE
Uncertainties of the fit parameters

### ISSUE THREAD

**Issue by JorisDeRidder** [geo-ant/varpro#23] opened 2023-07-25 15:22 UTC
Thanks for this very nice module!
I was wondering, is there a way to extract the estimated uncertainties of both the linear and the nonlinear model parameters? Looking into the algorithm description, it seems that you already computed all the ingredients needed to calculate the covariance matrix.

**Comment by geo-ant** [comment] 2023-07-25 20:42
Hey @JorisDeRidder, that's a great idea and I'd like to do that. I don't know how much time I'll have in the next couple of weeks for that, but if you want to contribute please feel invited. If you don't have time to contribute that's fine, too.  I'll try get to it at some point :)
 
One question that pops into my mind is: do you have a good idea how to write a test that gives me some confidence that the covariance matrix I calculated is correct?

**Comment by JorisDeRidder** [comment] 2023-07-28 14:04
My Rust skills are not yet at the level that I can (dare to) change the `varpro` code directly. What I can do, is to make an example dataset and model and estimate the parameter uncertainties and covariance matrix with a well-established statistical Python library (`lmfit`). Do you speak Python, or shall I post the output here directly in this thread?

**Comment by geo-ant** [comment] 2023-07-28 19:42
I'm super happy you're willing to help, even if it's not Rust code directly. I have dabbled in Python years ago and my skills are rudimentary but I should be able to read it. I'd be glad if we could add the python code for generating the ground truth data to the repo as well, not just the output. If you'd be willing to do that, that would be great. Just let me know and we can talk about how exactly we want to do that.

I just have one question about the covariance matrix. Do you think it should differ with the fitting method? Meaning should we expect a varpro solution to produce the same uncertainties as a purely nonlinear fit?

**Comment by geo-ant** [comment] 2023-09-13 06:18
hey @JorisDeRidder just wanted to let you know that I am working on the feature :) 

It's not gonna be fast but I know how to implement it but I still have to figure out a satisfying way to test it.

**Comment by JorisDeRidder** [comment] 2023-09-29 09:52
Hi @geo-ant, I have made a [Python notebook](https://github.com/JorisDeRidder/NonlinearRegression/blob/main/Uncertainties_nonlinear_regression.ipynb) where I explain how to compute the covariance matrix, and I apply it to a simple nonlinear model (a Gaussian function on top of a linear background). It contains concrete numbers you can use to compare your Rust version with. Would this be useful for your tests? Let me know if I can be any further help.

**Comment by geo-ant** [comment] 2023-09-29 16:23
Hey @JorisDeRidder that's awesome and I'll definitely check it out. And yes it will be useful for the tests. As a matter of fact I also brushed up on how to calculate the matrix and I have started the implementation on a feature branch. I also found a way to test it because a paper I used has Matlab code that also computes fit statistics. So I can use those results to crosscheck my calculations. 

The one thing that's holding me back right now is that I have to find a solution to express the dimensions of the covariance matrix that gels well with my use of generics 😅

But if you tell me you need that feature sooner than later I'll implement a less elegant solution first and try to make it cleaner in a future version. The actual calculations are not affected by that stuff anyhow.

**Comment by JorisDeRidder** [comment] 2023-10-02 14:19
Great, thanks! No need for a preliminary less elegant solution, I'm happy to wait for the final version.

**Comment by geo-ant** [comment] 2023-10-10 05:25
Hey @JorisDeRidder, I just wanted to give you a quick update. Your notebook was really helpful for getting back into the formulae, especially for the covariance matrix. I now can reproduce the results from the matlab code that accompanied the paper on which I based most of my implementation (meaning I based my implementation on the paper, not the matlab code :D). I still have one thing that I need to completely understand before I am confident enough to put my code out there. I contacted one of the original authors of the paper and she was kind enough to get back to me but an in depth response will take a couple more days. If you want I can try to explain what that particular thing is and you can also have a look.

**Comment by JorisDeRidder** [comment] 2023-10-11 07:56
Hi @geo-ant, if my very limited knowledge can be of any assistance, I'ld be happy to help.

**Comment by geo-ant** [comment] 2023-10-13 06:01
Hi, @JorisDeRidder. Professor O'Leary just answered the question I had. If you want, I can still explain what the confusion was, but I am confident I am doing the right thing now. The implementation is also shaping up, but I need to add documentation and tests still.

**Comment by geo-ant** [comment] 2023-10-15 19:47
Addressed in PR https://github.com/geo-ant/varpro/pull/24

**Comment by geo-ant** [comment] 2023-10-15 19:55
Version 0.7.0 now has a `statistics` module and functionality to `fit_with_statistics` in the `LevMarSolver`. Statistical information includes covariance matrix and some convenient helpers to extract the variance of the linear and nonlinear model parameters. 

Phew, that was more work than expected but I am happy to see it done :)

**Closed as completed by geo-ant** 2023-10-15 19:55 UTC
Labels: enhancement

**Comment by JorisDeRidder** [comment] 2023-10-16 08:40
Super, thanks!
